// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// StatsOKCode is the HTTP code returned for type StatsOK
const StatsOKCode int = 200

/*StatsOK Ok.

swagger:response statsOK
*/
type StatsOK struct {

	/*
	  In: Body
	*/
	Payload *StatsOKBody `json:"body,omitempty"`
}

// NewStatsOK creates StatsOK with default headers values
func NewStatsOK() *StatsOK {
	return &StatsOK{}
}

// WithPayload adds the payload to the stats o k response
func (o *StatsOK) WithPayload(payload *StatsOKBody) *StatsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the stats o k response
func (o *StatsOK) SetPayload(payload *StatsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StatsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// StatsInternalServerErrorCode is the HTTP code returned for type StatsInternalServerError
const StatsInternalServerErrorCode int = 500

/*StatsInternalServerError Internal error.

swagger:response statsInternalServerError
*/
type StatsInternalServerError struct{}

// NewStatsInternalServerError creates StatsInternalServerError with default headers values
func NewStatsInternalServerError() *StatsInternalServerError {
	return &StatsInternalServerError{}
}

// WriteResponse to the client
func (o *StatsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

// StatsServiceUnavailableCode is the HTTP code returned for type StatsServiceUnavailable
const StatsServiceUnavailableCode int = 503

/*StatsServiceUnavailable Not available.

swagger:response statsServiceUnavailable
*/
type StatsServiceUnavailable struct{}

// NewStatsServiceUnavailable creates StatsServiceUnavailable with default headers values
func NewStatsServiceUnavailable() *StatsServiceUnavailable {
	return &StatsServiceUnavailable{}
}

// WriteResponse to the client
func (o *StatsServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(503)
}
