apiVersion: v1
kind: Service
metadata:
  name: fizzbuzz
spec:
  selector:
    app: fizzbuzz
  ports:
  - name: api
    port: 80
    targetPort: api
  - name: metrics
    port: 7777
    targetPort: metrics
