// Code generated by go-swagger; DO NOT EDIT.

// Package restapi fizzbuzz
//
//  the service can apply fizzbuzz algorithm and statistics about the  calls.
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: #VERSION
//  Contact: pastequo@github
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
