// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/pastequo/services.fizzbuzz/models"
)

// NewFizzbuzzParams creates a new FizzbuzzParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFizzbuzzParams() *FizzbuzzParams {
	return &FizzbuzzParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFizzbuzzParamsWithTimeout creates a new FizzbuzzParams object
// with the ability to set a timeout on a request.
func NewFizzbuzzParamsWithTimeout(timeout time.Duration) *FizzbuzzParams {
	return &FizzbuzzParams{
		timeout: timeout,
	}
}

// NewFizzbuzzParamsWithContext creates a new FizzbuzzParams object
// with the ability to set a context for a request.
func NewFizzbuzzParamsWithContext(ctx context.Context) *FizzbuzzParams {
	return &FizzbuzzParams{
		Context: ctx,
	}
}

// NewFizzbuzzParamsWithHTTPClient creates a new FizzbuzzParams object
// with the ability to set a custom HTTPClient for a request.
func NewFizzbuzzParamsWithHTTPClient(client *http.Client) *FizzbuzzParams {
	return &FizzbuzzParams{
		HTTPClient: client,
	}
}

/* FizzbuzzParams contains all the parameters to send to the API endpoint
   for the fizzbuzz operation.

   Typically these are written to a http.Request.
*/
type FizzbuzzParams struct {

	/* FizzbuzzParams.

	   fizzbuzz algo parameter to use.
	*/
	FizzbuzzParams *models.FizzbuzzParams

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the fizzbuzz params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FizzbuzzParams) WithDefaults() *FizzbuzzParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the fizzbuzz params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FizzbuzzParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the fizzbuzz params
func (o *FizzbuzzParams) WithTimeout(timeout time.Duration) *FizzbuzzParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the fizzbuzz params
func (o *FizzbuzzParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the fizzbuzz params
func (o *FizzbuzzParams) WithContext(ctx context.Context) *FizzbuzzParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the fizzbuzz params
func (o *FizzbuzzParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the fizzbuzz params
func (o *FizzbuzzParams) WithHTTPClient(client *http.Client) *FizzbuzzParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the fizzbuzz params
func (o *FizzbuzzParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFizzbuzzParams adds the fizzbuzzParams to the fizzbuzz params
func (o *FizzbuzzParams) WithFizzbuzzParams(fizzbuzzParams *models.FizzbuzzParams) *FizzbuzzParams {
	o.SetFizzbuzzParams(fizzbuzzParams)
	return o
}

// SetFizzbuzzParams adds the fizzbuzzParams to the fizzbuzz params
func (o *FizzbuzzParams) SetFizzbuzzParams(fizzbuzzParams *models.FizzbuzzParams) {
	o.FizzbuzzParams = fizzbuzzParams
}

// WriteToRequest writes these params to a swagger request
func (o *FizzbuzzParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.FizzbuzzParams != nil {
		if err := r.SetBodyParam(o.FizzbuzzParams); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
