// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pastequo/services.fizzbuzz/models"
)

// FizzbuzzReader is a Reader for the Fizzbuzz structure.
type FizzbuzzReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FizzbuzzReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFizzbuzzOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewFizzbuzzNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewFizzbuzzBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewFizzbuzzInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewFizzbuzzServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewFizzbuzzOK creates a FizzbuzzOK with default headers values
func NewFizzbuzzOK() *FizzbuzzOK {
	return &FizzbuzzOK{}
}

/* FizzbuzzOK describes a response with status code 200, with default header values.

Successfully applied.
*/
type FizzbuzzOK struct {
	Payload string
}

func (o *FizzbuzzOK) Error() string {
	return fmt.Sprintf("[POST /algo/fizzbuzz][%d] fizzbuzzOK  %+v", 200, o.Payload)
}

func (o *FizzbuzzOK) GetPayload() string {
	return o.Payload
}

func (o *FizzbuzzOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFizzbuzzNoContent creates a FizzbuzzNoContent with default headers values
func NewFizzbuzzNoContent() *FizzbuzzNoContent {
	return &FizzbuzzNoContent{}
}

/* FizzbuzzNoContent describes a response with status code 204, with default header values.

Successfull but empty.
*/
type FizzbuzzNoContent struct{}

func (o *FizzbuzzNoContent) Error() string {
	return fmt.Sprintf("[POST /algo/fizzbuzz][%d] fizzbuzzNoContent ", 204)
}

func (o *FizzbuzzNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	return nil
}

// NewFizzbuzzBadRequest creates a FizzbuzzBadRequest with default headers values
func NewFizzbuzzBadRequest() *FizzbuzzBadRequest {
	return &FizzbuzzBadRequest{}
}

/* FizzbuzzBadRequest describes a response with status code 400, with default header values.

Bad request.
*/
type FizzbuzzBadRequest struct {
	Payload *models.ErrorMsg
}

func (o *FizzbuzzBadRequest) Error() string {
	return fmt.Sprintf("[POST /algo/fizzbuzz][%d] fizzbuzzBadRequest  %+v", 400, o.Payload)
}

func (o *FizzbuzzBadRequest) GetPayload() *models.ErrorMsg {
	return o.Payload
}

func (o *FizzbuzzBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	o.Payload = new(models.ErrorMsg)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFizzbuzzInternalServerError creates a FizzbuzzInternalServerError with default headers values
func NewFizzbuzzInternalServerError() *FizzbuzzInternalServerError {
	return &FizzbuzzInternalServerError{}
}

/* FizzbuzzInternalServerError describes a response with status code 500, with default header values.

Internal error.
*/
type FizzbuzzInternalServerError struct{}

func (o *FizzbuzzInternalServerError) Error() string {
	return fmt.Sprintf("[POST /algo/fizzbuzz][%d] fizzbuzzInternalServerError ", 500)
}

func (o *FizzbuzzInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	return nil
}

// NewFizzbuzzServiceUnavailable creates a FizzbuzzServiceUnavailable with default headers values
func NewFizzbuzzServiceUnavailable() *FizzbuzzServiceUnavailable {
	return &FizzbuzzServiceUnavailable{}
}

/* FizzbuzzServiceUnavailable describes a response with status code 503, with default header values.

Not available.
*/
type FizzbuzzServiceUnavailable struct{}

func (o *FizzbuzzServiceUnavailable) Error() string {
	return fmt.Sprintf("[POST /algo/fizzbuzz][%d] fizzbuzzServiceUnavailable ", 503)
}

func (o *FizzbuzzServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	return nil
}
