// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStatsParams creates a new StatsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStatsParams() *StatsParams {
	return &StatsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStatsParamsWithTimeout creates a new StatsParams object
// with the ability to set a timeout on a request.
func NewStatsParamsWithTimeout(timeout time.Duration) *StatsParams {
	return &StatsParams{
		timeout: timeout,
	}
}

// NewStatsParamsWithContext creates a new StatsParams object
// with the ability to set a context for a request.
func NewStatsParamsWithContext(ctx context.Context) *StatsParams {
	return &StatsParams{
		Context: ctx,
	}
}

// NewStatsParamsWithHTTPClient creates a new StatsParams object
// with the ability to set a custom HTTPClient for a request.
func NewStatsParamsWithHTTPClient(client *http.Client) *StatsParams {
	return &StatsParams{
		HTTPClient: client,
	}
}

/* StatsParams contains all the parameters to send to the API endpoint
   for the stats operation.

   Typically these are written to a http.Request.
*/
type StatsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the stats params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StatsParams) WithDefaults() *StatsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the stats params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StatsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the stats params
func (o *StatsParams) WithTimeout(timeout time.Duration) *StatsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stats params
func (o *StatsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stats params
func (o *StatsParams) WithContext(ctx context.Context) *StatsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stats params
func (o *StatsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stats params
func (o *StatsParams) WithHTTPClient(client *http.Client) *StatsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stats params
func (o *StatsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *StatsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
